name: Generate GitHub Trophies

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate trophies SVG
    steps:
      - uses: actions/checkout@v4

      - name: Generate trophy card
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=MABAIStrategies&theme=radical&column=7&no-frame=true&no-bg=true'
          path: profile/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit trophies SVG
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update GitHub trophies SVG"
          add: "profile/trophy.svg"
